### ISSUE TITLE
Slack invite link is broken and not working

### ISSUE THREAD

**Issue by ericbrumfield** [zeek/zeek-docs#118]
Hello,

The slack workspace invite link I attempted to use appears to be broken on the zeek.org site and in the documentation:
https://join.slack.com/t/zeekorg/shared_invite/zt-12z1pjy93-zuVGuT1BF~yUJJvERxhp7g

**Comment by ckreibich** [comment]
Thanks Eric — what are you seeing when you click it? I just tried and it seems to do what it should. I didn't try a new sign-up, just visited the link.

**Comment by ckreibich** [comment]
Looks like it's indeed about the sign-up. We're looking into it.

**Comment by ckreibich** [comment]
I'm not sure it'll achieve much, but I've pinged Slack support. Cross fingers.

**Comment by ckreibich** [comment]
This was semi-successful — it doesn't look like they have (or are willing to provide) a simple forever-invite link, but they've offered the following:

https://join.slack.com/t/zeekorg/shared_invite/zt-1ev1nr7z4-rEVSsaIzYzFWpdgh2I6ZOg

It's valid for up to 2,000 sign-ups and expires on Friday, August 18th at 6:46 PM. We'll need to remember that, but otherwise it seems like an improvement. Thoughts?

**Comment by ckreibich** [comment]
August 18th 2023, that is. :-)

**Comment by ckreibich** [comment]
This is now live on the website.
