### ISSUE TITLE
advertise docker as installation method

### ISSUE THREAD

**Issue by falcorocks** [zeek/zeek-docs#134]
Hey guys,
* At first, I was surprised to not find docker as an advertised method for installation in https://docs.zeek.org/en/master/install.html ...
* Then I found several unofficial zeek images in dockerhub ... 
* Then I went in your CI logs at the main repo and saw that you do have jobs to build and publish official images which finally led me to what I believe is the official repo (is it??): https://hub.docker.com/r/zeekurity/zeek

To me it seems a no brainer to advertise the dockerhub link in the install page, perhaps with one or two examples of how to run it... You do all the hard work of building the container images and then it's not in the docs where one would expect it to find it! 😅  even just a one liner with a link would be good enough!

**Comment by ckreibich** [comment]
You're right to point this out. We've been slow to advertise the images on Dockerhub because we're not sure we'll stick with Dockerhub as the official repo, due to the severe constraints they impose on open source projects. We've repeatedly tried to improve that situation to no avail, and as a result we're currently looking into the AWS ECR as an alternative. Unfortunately this has dragged on long enough that the situation now looks confusing.

To be clear: the Docker images at https://hub.docker.com/u/zeekurity are our official ones.

We're hoping to resolve all this in the very near future, and cover it in the docs accordingly.
